spring:
  application:
    name: ONBOARDING-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8088

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    root: info
    by.javaguru.jdmik13.onboardingservice: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: TRACE

client:
  feign:
    security-service: http://SECURITY-SERVICE
    account-service: http://ACCOUNTING-SERVICE
    # profiler-service: http://PROFILER-SERVICE

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        ignore-exceptions:
          - by.javaguru.jdmik13.onboardingservice.client.exception.BudgetAllocationException
          - by.javaguru.jdmik13.onboardingservice.client.exception.SecurityCheckException
    instances:
      accountServiceCircuitBreaker:
        baseConfig: default
        wait-duration-in-open-state: 6s
      securityServiceCircuitBreaker:
        baseConfig: default
        wait-duration-in-open-state: 7s
    circuit-breaker-aspect-order: 1

  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 1000ms
    retry-aspect-order: 2

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    enabled: true # Enables Micrometer tracing
    sampling:
      probability: 1.0 # Sample all traces
    propagation:
      type: w3c
 
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://localhost:4318/v1/traces}

